### ISSUE TITLE
App not installed 

### ISSUE THREAD

**Issue by Abdul-Quadri-Ismail** [YunsGeek/Quraan-Player#4]
As salaam alaikum,

After downloading the APK from the link provided, anytime I try to install the app am getting App not installed.

Device Info
Device name: A3_PRO
Android Version : 9
Brand name : UMIDIGI

**Comment by YunsGeek** [comment]
assalam aliykum .
thank you for your report !
the issue is your phone CPU architecture is different a little i think is ( ARMv8-A 64-bit ) , 
try this version it should work ( ARMv8-A 64-bit ) if not try the others version :

- link for donwload (arm64-v8a cpu apk) : https://bit.ly/Quran-Player1-0-1-arm64-v8a
- link for donwload (x86 cpu apk) : https://bit.ly/Quran-Player1-0-1-x86
- link for donwload (x86_64 cpu apk) : https://bit.ly/Quran-Player1-0-1-x86_64
- link for donwload (armeabi-v7a apk) : https://bit.ly/Quran-Player1-0-1-armeabi-v7a

thank you soo much , have a nice day !
